In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
path_2012 = r"Tabela5-sem_emprego_2012.csv"

t2012 = pd.read_csv(
    path_2012,
    sep=";",
    decimal=",",
    encoding="utf-8-sig"
)

t2012.head()

,Sigla,Código,Estado,Desocupados - homens (2012 T1),Desocupados - mulheres (2012 T1)
0,AC,12,Acre,45.3,54.7
1,AL,27,Alagoas,44.7,55.3
2,AM,13,Amazonas,47.5,52.5
3,AP,16,Amapá,48.1,51.9
4,BA,29,Bahia,43.8,56.2

In [7]:
path_2026 = r"Tabela5-sem_emprego_2026.csv"

t2026 = pd.read_csv(
    path_2026,
    sep=";",
    decimal=",",
    encoding="utf-8-sig"
)

t2026.head()

,Sigla,Código,Estado,Desocupados - homens (2026 T1),Desocupados - mulheres (2026 T1)
0,AC,12,Acre,53.2,46.8
1,AL,27,Alagoas,50.7,49.3
2,AM,13,Amazonas,46.8,53.2
3,AP,16,Amapá,51.1,48.9
4,BA,29,Bahia,44.7,55.3

In [8]:
comp = t2012.merge(
    t2026,
    on=["Sigla", "Código", "Estado"],
    how="inner"
)

comp.head()

,Sigla,Código,Estado,Desocupados - homens (2012 T1),Desocupados - mulheres (2012 T1),Desocupados - homens (2026 T1),Desocupados - mulheres (2026 T1)
0,AC,12,Acre,45.3,54.7,53.2,46.8
1,AL,27,Alagoas,44.7,55.3,50.7,49.3
2,AM,13,Amazonas,47.5,52.5,46.8,53.2
3,AP,16,Amapá,48.1,51.9,51.1,48.9
4,BA,29,Bahia,43.8,56.2,44.7,55.3

In [9]:
comp.info()

<class 'pandas.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 7 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Sigla                             27 non-null     str
 1   Código                            27 non-null     int64
 2   Estado                            27 non-null     str
 3   Desocupados - homens (2012 T1)    27 non-null     float64
 4   Desocupados - mulheres (2012 T1)  27 non-null     float64
 5   Desocupados - homens (2026 T1)    27 non-null     float64
 6   Desocupados - mulheres (2026 T1)  27 non-null     float64
dtypes: float64(4), int64(1), str(2)
memory usage: 1.6 KB

In [10]:
comp["Diferença homens"] = (
    comp["Desocupados - homens (2026 T1)"] -
    comp["Desocupados - homens (2012 T1)"]
)

comp[[
    "Sigla",
    "Estado",
    "Desocupados - homens (2012 T1)",
    "Desocupados - homens (2026 T1)",
    "Diferença homens"
]]

,Sigla,Estado,Desocupados - homens (2012 T1),Desocupados - homens (2026 T1),Diferença homens
0,AC,Acre,45.3,53.2,7.9
1,AL,Alagoas,44.7,50.7,6.0
2,AM,Amazonas,47.5,46.8,-0.7
3,AP,Amapá,48.1,51.1,3.0
4,BA,Bahia,43.8,44.7,0.9
5,CE,Ceará,51.1,52.7,1.6
6,DF,Distrito Federal,41.0,47.9,6.9
7,ES,Espírito Santo,46.4,47.5,1.1
8,GO,Goiás,41.0,47.5,6.5
9,MA,Maranhão,47.2,49.1,1.9
10,MG,Minas Gerais,43.1,48.6,5.5
11,MS,Mato Grosso do Sul,47.2,45.3,-1.9
12,MT,Mato Grosso,44.1,42.8,-1.3
13,PA,Pará,43.2,48.3,5.1
14,PB,Paraíba,44.4,48.9,4.5
15,PE,Pernambuco,43.9,48.7,4.8
16,PI,Piauí,51.2,55.1,3.9
17,PR,Paraná,40.3,46.3,6.0
18,RJ,Rio de Janeiro,44.2,45.4,1.2
19,RN,Rio Grande do Norte,51.0,48.2,-2.8
20,RO,Rondônia,43.4,33.0,-10.4
21,RR,Roraima,41.8,43.4,1.6
22,RS,Rio Grande do Sul,42.8,47.4,4.6
23,SC,Santa Catarina,42.7,44.6,1.9
24,SE,Sergipe,46.5,40.3,-6.2
25,SP,São Paulo,45.4,46.2,0.8
26,TO,Tocantins,55.3,46.2,-9.1

In [11]:
comp["Diferença mulheres"] = (
    comp["Desocupados - mulheres (2026 T1)"] -
    comp["Desocupados - mulheres (2012 T1)"]
)

comp[[
    "Sigla",
    "Estado",
    "Desocupados - mulheres (2012 T1)",
    "Desocupados - mulheres (2026 T1)",
    "Diferença mulheres"
]]

,Sigla,Estado,Desocupados - mulheres (2012 T1),Desocupados - mulheres (2026 T1),Diferença mulheres
0,AC,Acre,54.7,46.8,-7.9
1,AL,Alagoas,55.3,49.3,-6.0
2,AM,Amazonas,52.5,53.2,0.7
3,AP,Amapá,51.9,48.9,-3.0
4,BA,Bahia,56.2,55.3,-0.9
5,CE,Ceará,48.9,47.3,-1.6
6,DF,Distrito Federal,59.0,52.1,-6.9
7,ES,Espírito Santo,53.6,52.5,-1.1
8,GO,Goiás,59.0,52.5,-6.5
9,MA,Maranhão,52.8,50.9,-1.9
10,MG,Minas Gerais,56.9,51.4,-5.5
11,MS,Mato Grosso do Sul,52.8,54.7,1.9
12,MT,Mato Grosso,55.9,57.2,1.3
13,PA,Pará,56.8,51.7,-5.1
14,PB,Paraíba,55.6,51.1,-4.5
15,PE,Pernambuco,56.1,51.3,-4.8
16,PI,Piauí,48.8,44.9,-3.9
17,PR,Paraná,59.7,53.7,-6.0
18,RJ,Rio de Janeiro,55.8,54.6,-1.2
19,RN,Rio Grande do Norte,49.0,51.8,2.8
20,RO,Rondônia,56.6,67.0,10.4
21,RR,Roraima,58.2,56.6,-1.6
22,RS,Rio Grande do Sul,57.2,52.6,-4.6
23,SC,Santa Catarina,57.3,55.4,-1.9
24,SE,Sergipe,53.5,59.7,6.2
25,SP,São Paulo,54.6,53.8,-0.8
26,TO,Tocantins,44.7,53.8,9.1

In [12]:
comp.sort_values(
    "Diferença homens",
    ascending=False
)[[
    "Sigla",
    "Estado",
    "Diferença homens"
]]

   Sigla               Estado  Diferença homens
0     AC                 Acre               7.9
6     DF     Distrito Federal               6.9
8     GO                Goiás               6.5
1     AL              Alagoas               6.0
17    PR               Paraná               6.0
10    MG         Minas Gerais               5.5
13    PA                 Pará               5.1
15    PE           Pernambuco               4.8
22    RS    Rio Grande do Sul               4.6
14    PB              Paraíba               4.5
16    PI                Piauí               3.9
3     AP                Amapá               3.0
9     MA             Maranhão               1.9
23    SC       Santa Catarina               1.9
5     CE                Ceará               1.6
21    RR              Roraima               1.6
18    RJ       Rio de Janeiro               1.2
7     ES       Espírito Santo               1.1
4     BA                Bahia               0.9
25    SP            São Paulo               0.8
2     AM             Amazonas              -0.7
12    MT          Mato Grosso              -1.3
11    MS   Mato Grosso do Sul              -1.9
19    RN  Rio Grande do Norte              -2.8
24    SE              Sergipe              -6.2
26    TO            Tocantins              -9.1
20    RO             Rondônia             -10.4

In [13]:
comp.sort_values(
    "Diferença mulheres",
    ascending=False
)[[
    "Sigla",
    "Estado",
    "Diferença mulheres"
]]

   Sigla               Estado  Diferença mulheres
20    RO             Rondônia                10.4
26    TO            Tocantins                 9.1
24    SE              Sergipe                 6.2
19    RN  Rio Grande do Norte                 2.8
11    MS   Mato Grosso do Sul                 1.9
12    MT          Mato Grosso                 1.3
2     AM             Amazonas                 0.7
25    SP            São Paulo                -0.8
4     BA                Bahia                -0.9
7     ES       Espírito Santo                -1.1
18    RJ       Rio de Janeiro                -1.2
21    RR              Roraima                -1.6
5     CE                Ceará                -1.6
9     MA             Maranhão                -1.9
23    SC       Santa Catarina                -1.9
3     AP                Amapá                -3.0
16    PI                Piauí                -3.9
14    PB              Paraíba                -4.5
22    RS    Rio Grande do Sul                -4.6
15    PE           Pernambuco                -4.8
13    PA                 Pará                -5.1
10    MG         Minas Gerais                -5.5
1     AL              Alagoas                -6.0
17    PR               Paraná                -6.0
8     GO                Goiás                -6.5
6     DF     Distrito Federal                -6.9
0     AC                 Acre                -7.9

In [19]:
df.columns = [
    "Estado",
    "Total",
    "Mulher branca",
    "Mulher preta ou parda",
    "Homem branco",
    "Homem preto ou pardo",
    "Mulher branca 2",
    "Mulher preta ou parda 2"
]

df.head()

,Estado,Total,Mulher branca,Mulher preta ou parda,Homem branco,Homem preto ou pardo,Mulher branca 2,Mulher preta ou parda 2
0,Brasil,16.985781,16.545930,17.333142,11.705136,11.746330,20.404106,22.037998
1,Norte,16.187037,15.925246,16.256032,11.588653,11.514646,19.295780,20.534188
2,Rondônia,17.014162,16.727733,17.101523,12.111127,12.544080,20.412887,21.061410
3,Acre,13.606903,13.806929,13.541399,10.796120,9.686983,16.130352,16.710754
4,Amazonas,16.807290,15.987545,16.995493,12.233043,12.822584,18.764969,20.716986

In [23]:
df.columns = [
    "Estado",
    "Total",
    "Homem branco",
    "Homem preto ou pardo",
    "Homem branco",
    "Homem preto ou pardo",
    "Mulher branca",
    "Mulher preta ou parda"
]

df.head()

,Estado,Total,Homem branco,Homem preto ou pardo,Homem branco,Homem preto ou pardo,Mulher branca,Mulher preta ou parda
0,Brasil,16.985781,16.545930,17.333142,11.705136,11.746330,20.404106,22.037998
1,Norte,16.187037,15.925246,16.256032,11.588653,11.514646,19.295780,20.534188
2,Rondônia,17.014162,16.727733,17.101523,12.111127,12.544080,20.412887,21.061410
3,Acre,13.606903,13.806929,13.541399,10.796120,9.686983,16.130352,16.710754
4,Amazonas,16.807290,15.987545,16.995493,12.233043,12.822584,18.764969,20.716986

In [25]:
print(df.columns)

Index(['Estado', 'Total', 'Homem branco', 'Homem preto ou pardo',
       'Homem branco', 'Homem preto ou pardo', 'Mulher branca',
       'Mulher preta ou parda'],
      dtype='str')